version: '2'
services:
    tpims-app:
        image: tpims
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://tpims-postgresql:5432/tpims
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=tpims-elasticsearch:9300
        ports:
            - 8080:8080
    tpims-postgresql:
        extends:
            file: postgresql.yml
            service: tpims-postgresql
    tpims-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: tpims-elasticsearch
